version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      
  build:
    commands:
      - npm run build -- --env ${CURRENT_ENVIRONMENT}
