version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
  build:
    commands:
  artifacts:
    files:
      - '**/*'
    name: s3-to-s3-latest-build.zip  
